### ISSUE TITLE
Αποθήκευσε τα αποτελεσματα του API

### ISSUE THREAD

**Issue by PrekWood** [PrekWood/onlineDiagnosis#2]
Κανε μια κληση σε καθε επίπεδο του api και αποθήκευσε τα αποτελέσματα του σε ενα json για να μην βαράμε συνέχεια το api και όπου χρειαζομαστε δεδομένα θα τα διαβαζεις απο εδώ (ανεξάρτητα απο το id)

πχ 
```
/api_responses/locations.json
/api_responses/subLocations.json
/api_responses/symptoms.json
```
κτλ

![image](https://user-images.githubusercontent.com/46693693/169877600-e904ad33-9665-409c-bc34-aa4d84db85b7.png)

**Comment by IliasBrinias** [comment]
online_diagnosis_body_location.csv
online_diagnosis_body_sub_locations.csv
online_diagnosis_symptoms.csv
are allready created
